
metadata:
  name: rosa-osd-edit-app-ingress
  instructional: true
spec:
  displayName: Editing your managed OpenShift cluster's application ingress
  durationMinutes: 5
  type:
    text: Quick start
    color: green
  icon: data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQ0OCA2NHY0MTZoLTMzNmMtMjYuNTEzIDAtNDgtMjEuNDktNDgtNDhzMjEuNDg3LTQ4IDQ4LTQ4aDMwNHYtMzg0aC0zMjBjLTM1LjE5OSAwLTY0IDI4LjgtNjQgNjR2Mzg0YzAgMzUuMiAyOC44MDEgNjQgNjQgNjRoMzg0di00NDhoLTMyeiI+PC9wYXRoPgo8cGF0aCBkPSJNMTEyLjAyOCA0MTZ2MGMtMC4wMDkgMC4wMDEtMC4wMTkgMC0wLjAyOCAwLTguODM2IDAtMTYgNy4xNjMtMTYgMTZzNy4xNjQgMTYgMTYgMTZjMC4wMDkgMCAwLjAxOS0wLjAwMSAwLjAyOC0wLjAwMXYwLjAwMWgzMDMuOTQ1di0zMmgtMzAzLjk0NXoiPjwvcGF0aD4KPC9zdmc+Cg==
  prerequisites:
    - You must have a Red Hat OpenShift Service on AWS or OpenShift Dedicated cluster.
    - You must be a cluster owner, cluster editor, or Organization Administrator for the cluster.

  description: |-
    Edit the application ingress of your managed OpenShift cluster after creation.
  introduction: |-
    Using OpenShift Cluster Manager, you can edit the application ingress of your Red Hat OpenShift Service on Amazon Web Services or Red Hat OpenShift Dedicated clusters. In this quick start, you'll learn how to edit your ROSA or OpenShift Dedicated cluster's application ingress.

    [In this quickstart, Red Hat OpenShift Service on AWS refers to both Red Hat OpenShift Service on AWS classic architecture and Red Hat OpenShift Service on AWS, and OpenShift Dedicated refers to both OpenShift Dedicated on Google Cloud and OpenShift Dedicated on AWS.]{{admonition note}}

  tasks:
    - title: Edit application ingress for your cluster
      description: |-
        To edit your cluster's application ingress:

        1. Go to **Cluster List**.
        1. Click your cluster's name to view the cluster details.
        1. Click the **Networking** tab.
        1. In the **Application Ingress** section, click the **Edit application ingress** button.

            a. You can change the Default application router if needed.

            b. Click the checkbox if you want to make your router private.

        1. Click **Save** to finalize your changes.

  # optional - the task's Check your work module
      review:
        instructions: |-
          - Does your cluster display the new application ingress you changed it to?
        failedTaskHelp: Try following the steps again.
  # optional - the task's success and failure messages
      summary:
        success: Shows a success message in the task header
        failed: Shows a failed message in the task header
  conclusion: |-
        Congratulations, you've edited your cluster's application ingress!

        You can edit your cluster's application ingress as often as needed.
  # you can link to the next quick start(s) here
