apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: rbac-configuring-access
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Setting up User Access
  icon: ~
  description: Configuring role-based access control (RBAC) for services hosted on the Hybrid Cloud Console
  link:
    href: https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/2023/html/user_access_configuration_guide_for_role-based_access_control_rbac/index
    text: View documentation
